### ISSUE TITLE
Lagging behind ROCm-docker

### ISSUE THREAD

**Issue by acowley** [RadeonOpenCompute/ROCm-OpenCL-Runtime#50]
On an rx580, a container based on ROCm-docker `rocm-terminal` shows,

```
Platform Version                                OpenCL 2.1 AMD-APP.internal (2576.0)
```

in `clinfo`. More critically, it also shows,

```
Image support                                   Yes
```

On my host system, I build from the 1.7 release and have,

```
CL_PLATFORM_VERSION: OpenCL 2.0 AMD-APP.internal (2545.0)
...
CL_DEVICE_IMAGE_SUPPORT: false
```

I've looked at the various branches here, but I can't find a commit with a build number newer than 2545. Would it be possible to sync the internal repo used to produce build 2576 with the github repositories?

Thank you!

**Comment by kzhuravl** [comment]
+ @lmoriche 

Hi, I am in the process of updating opencl runtime github repo up to 2576.

**Comment by acowley** [comment]
Thank you, @kzhuravl, that is great news! I'd be happy to test beta releases in general, but I am building against rocm on a NixOS machine using [this packaging](https://github.com/peter-sa/nixos-rocm). So consider this a vote to automate regular pushing to a beta branch here on GitHub 😀

**Comment by kzhuravl** [comment]
Hi @acowley , I believe the issue was fixed a few days ago by this commit:
https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/commit/3b1829cbdc2c711c7a975339c721e961baf37397

`+` @lmoriche, @gstoner to consider pushing regular/beta commits to github.

**Comment by acowley** [comment]
Thank you for pushing things along @kzhuravl! I've been tracking your pushes, and the build number is indeed up to date. I am still missing image support on my host system, while it works in the docker container and I do not know how to further debug that. Is the `amd-common` branch a good one to track for the llvm tools, or should I expect it to break things in repos like this one that do not have an `amd-common` branch?

If you have any suggestions for debugging the different capabilities of my host system vs the docker container (host is NixOS running kernel 4.13) I'd be more than thankful, but I appreciate that this is not strictly within the footprint of intended support.

Thank you!

**Comment by acowley** [comment]
It would be nice if there was a common branch naming scheme for these repos to indicate compatibility. I can't build the 1.7.1 release of the relevant things against the `amd-common` branch of the LLVM tools.

Today's attempt:

```
/tmp/nix-build-rocm-opencl-runtime-1.7.1.drv-0/ROCm-OpenCL-Runtime-roc-1.7.1-src/library/amdgcn/utils/prepare-builtins/prepare-builtins.cpp:124:3: error: no matching function for call to 'WriteBitcodeToFile'
  WriteBitcodeToFile(M, Out->os());
  ^~~~~~~~~~~~~~~~~~
/tmp/nix-build-rocm-opencl-runtime-1.7.1.drv-0/ROCm-OpenCL-Runtime-roc-1.7.1-src/compiler/llvm/include/llvm/Bitcode/BitcodeWriter.h:129:8: note: candidate function not viable: no known conversion from 'llvm::Module *' to 'const llvm::Module' for 1st argument; dereference the argument with *
  void WriteBitcodeToFile(const Module &M, raw_ostream &Out,
       ^
```

**Comment by kzhuravl** [comment]
Hi @acowley.

We never intended to build 1.7.1 branches (or other releases) against amd-common branches of llvm. If you are using release branches, all code should come from the same release.

If you want to build with amd-common branches of llvm/clang/lld, which are updated regularly, you should use master branches of
  - https://github.com/KhronosGroup/OpenCL-ICD-Loader
  - https://github.com/RadeonOpenCompute/ROCm-Device-Libs
  - https://github.com/RadeonOpenCompute/ROCm-OpenCL-Driver
  - https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime

I suggest using this manifest file (it is used in our jenkins jobs):
https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/blob/master/opencl.xml

Before we push updates to the amd-common branch of llvm/clang/lld, we do make sure everything builds (debug, release builds), and passes a pre-defined set of tests. So it should never be broken :)

The reason for naming llvm/clang/lld branches "amd-common" is to not confuse those with "master" branches of llvm/clang/lld (trunk). We do have a minor delta between "amd-common" and trunk on which we are working on.

Hope that helps, let me know if not!

I will also try and find something out about image support and NixOS tomorrow.

**Comment by acowley** [comment]
Thank you for clarifying, @kzhuravl! I have an `hcc` NixOS package just about working (I can run it out of my build tree), so NixOS support for the various ROCm pieces is coming along. 

Regarding OpenCL image support, the seemingly best clue I've been able to find to distinguish the host NixOS environment from the docker container is the `Platform Version` reported by `clinfo` I mentioned at the top of this thread. Given the recent updates, `clinfo` running on the NixOS host system reports,

```
Platform Version:				 OpenCL 2.0 AMD-APP.internal (2576.0)
```

While the docker container continues to report,

```
Platform Version                                OpenCL 2.1 AMD-APP.internal (2576.0)
```

I haven't been able to track down where this data comes from to see if that would point me to the culprit.
